# Done to increase the memory available to gradle.
	org.gradle.jvmargs=-Xmx1G

# Fabric Properties
# check these on https://fabricmc.net/develop
	minecraft_version=1.21
	yarn_mappings=1.21+build.2
	loader_version=0.15.11

# Fabric api
	fabric_version=0.100.3+1.21

# Mod Menu
	modmenu_version=11.0.1

# Cloth Config
	cloth_config_version=15.0.127

# Litematica (CurseForge file ID's)
	litematica_version=5450189
	malilib_version=5427775

# Mod Properties
	mod_version = 1.10.29
	maven_group = io.github.sjouwer
	archives_base_name = Pick-Block-Pro
